// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxciqhnegdxyohsrtpgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4Y2lxaG5lZ2R4eW9oc3J0cGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mzg1NjksImV4cCI6MjA1OTQxNDU2OX0.hjxbfPq3gDiDr-O6m0TCSR2CnwmzbrTWzwXBitcE1Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);